apiVersion: v1
entries:
  openfaas:
  - apiVersion: v2
    created: "2024-03-06T00:03:10.503332488Z"
    description: OpenFaaS - Serverless Functions Made Simple
    digest: e10ff4d1d152a7fe60988c332ff66a92d72f329beb6ca73e2cb537b078a04371
    home: https://www.openfaas.com
    icon: https://raw.githubusercontent.com/openfaas/media/master/OpenFaaS_logo_stacked_opaque.png
    keywords:
    - serverless
    - functions
    - platform
    - faas
    maintainers:
    - email: innoobi@cs.washington.edu
      name: innoobi
    name: openfaas
    sources:
    - https://github.com/innoobijr/faas
    - https://github.com/innoobijr/faas-netes
    type: application
    urls:
    - https://innoobijr.github.io/faas-netes/openfaas-14.2.25.tgz
    version: 14.2.25
generated: "2024-03-06T00:03:10.500983524Z"
